# Changes here will be overwritten by Copier
AddPrecommitUpdateCI: true
Authors: Stefan de Lange <langestefan@msn.com>
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Stefan de Lange
PackageName: ProbabilisticPowerFlow
PackageOwner: langestefan
PackageUUID: 7a0bcd8a-99c7-5dfb-8863-9081db092720
StrategyConfirmIncluded: false
StrategyLevel: 3
StrategyReviewExcluded: false
_src_path: /home/sdelange/.julia/packages/BestieTemplate/wBn4Z
