name = "ProbabilisticPowerFlow"
uuid = "7a0bcd8a-99c7-5dfb-8863-9081db092720"
version = "0.1.0"
authors = ["Stefan de Lange <langestefan@msn.com>"]

[workspace]
projects = ["test", "docs", "benchmark"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Copulas = "ae264745-0b69-425e-9d9d-cf662c5eec93"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[extensions]
PPFCopulasExt = "Copulas"
PPFPowerModelsExt = "PowerModels"
PPFQuasiMonteCarloExt = "QuasiMonteCarlo"
PPFSobolExt = "Sobol"

[compat]
Copulas = "0.1.33"
Distributions = "0.25"
LinearAlgebra = "1.10"
PowerModels = "0.21"
QuasiMonteCarlo = "0.3"
Random = "1.10"
Sobol = "1.5"
Statistics = "1.10"
julia = "1.10"
